# Generated by Django 2.2.6 on 2019-10-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
