# Generated by Django 2.2.6 on 2019-10-30 02:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mentor',
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.05000000000000000277555756156289135105907917022705078125'), max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.0299999999999999988897769753748434595763683319091796875'), max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=Decimal('0.0200000000000000004163336342344337026588618755340576171875'), max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('audit_prob_user', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('open_tasks', models.IntegerField(default=0, max_length=10000)),
                ('completed_tasks', models.IntegerField(default=0, max_length=10000)),
                ('claimed_tasks', models.IntegerField(default=0, max_length=10000)),
                ('worker_pool', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
