# Generated by Django 2.2.6 on 2019-10-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191030_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audit_prob_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='worker_pool',
        ),
    ]
