# Generated by Django 2.2.6 on 2019-10-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auditor_tu'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_Mentor',
            field=models.BooleanField(default=False),
        ),
    ]
