# Generated by Django 2.2.6 on 2019-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191113_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
