# Generated by Django 2.2.6 on 2019-11-10 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='worker_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskUserJunction'),
            preserve_default=False,
        ),
    ]
