# Generated by Django 2.2.6 on 2019-11-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_worker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='worker_id',
        ),
    ]
