# Generated by Django 2.2.6 on 2019-12-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='star',
            field=models.CharField(default='unstar', max_length=255),
        ),
    ]
