# Generated by Django 2.2.6 on 2019-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuserjunction',
            name='room_id',
            field=models.IntegerField(default=0),
        ),
    ]
